# Generated by Django 3.2.5 on 2021-07-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210719_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='currently_working',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profession',
        ),
    ]
